apiVersion: v1
kind: Pod
metadata:
  name: ws-server
spec:
  containers:
  - name: ws-server
    image: ws_server:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    livenessProbe: 
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 20
      periodSeconds: 10
  imagePullSecrets:
  - name: <contaire-regitry-secret-name>

